heartbeat.monitors:

#Monitor all containers using an icmp ping
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["filebeat","metricbeat","packetbeat","auditbeat","heartbeat","logstash","elasticsearch-1","elasticsearch-2","elasticsearch-3","kibana"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  wait: 1s

#Monitor the Elasticsearch instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["${ELASTICSEARCH_HOSTS}"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  check.request:
    method: "GET"
  check.response:
    status: 200

#Monitor the Kibana instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["${KIBANA_HOST}"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response:
    status: 200

processors:
- add_docker_metadata: ~

logging.to_files: false

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Xpack Monitoring ===============================
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["${ELASTICSEARCH_HOSTS}"]
monitoring.elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
monitoring.elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
