# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml

#-------------------------------- Autodiscovery -------------------------------
# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
metricbeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

metricbeat.modules:
#------------------------------- System Module -------------------------------
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#------------------------------- Stack Module -------------------------------

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: elasticsearch-1
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_USERNAME}

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: elasticsearch-2
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_USERNAME}

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: elasticsearch-3
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_USERNAME}

- module: kibana
  metricsets: 
    - stats
  period: 10s
  hosts: kibana
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_USERNAME}
  xpack.enabled: true

- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: logstash


- module: beat
  xpack.enabled: true
  period: 10s
  hosts: filebeat

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: metricbeat

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: packetbeat

- module: beat
  xpack.enabled: true
  period: 10s
  hosts: heartbeat

#------------------------------- Docker Module -------------------------------

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch: