network.host: 0.0.0.0
cluster.name: docker-cluster
bootstrap.memory_lock: true

discovery.type: single-node
node.name: elasticsearch
node.master: true
node.data: true
node.ingest: true
node.attr.temp: hot

xpack.security.enabled: true
xpack.license.self_generated.type: basic
xpack.monitoring.collection.enabled: true
xpack.security.audit.enabled: true