# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

#- pipeline.id: main
#  path.config: "/usr/share/logstash/pipeline"

- pipeline.id: container
  queue.type: persisted
  pipeline.workers: 4
  pipeline.batch.size: 1000
  path.config: "/usr/share/logstash/pipeline/contianer-pipeline.conf"

- pipeline.id: linux
  queue.type: persisted
  pipeline.workers: 4
  pipeline.batch.size: 1000
  path.config: "/usr/share/logstash/pipeline/linux-pipeline.conf"

- pipeline.id: docker
  queue.type: persisted
  pipeline.workers: 4
  pipeline.batch.size: 1000
  path.config: "/usr/share/logstash/pipeline/docker-pipeline.conf"

- pipeline.id: beats
  queue.type: persisted
  pipeline.workers: 4
  pipeline.batch.size: 1000
  path.config: "/usr/share/logstash/pipeline/beats-pipeline.conf"

- pipeline.id: shelf
  queue.type: persisted
  pipeline.workers: 4
  pipeline.batch.size: 1000
  path.config: "/usr/share/logstash/pipeline/shelf-pipeline.conf"