version: '3.7'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:1.2.3
    container_name: opensearch-node1
    restart: always
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1
      - network.host=0.0.0.0
    healthcheck:
      test: curl -s  http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./volume/opensearch-data1:/usr/share/opensearch/data
      - ./volume/opensearch-data1-config:/usr/share/opensearch/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
    logging:
      options:
        max-size: "10m"

  opensearch-node2:
    image: opensearchproject/opensearch:1.2.3
    container_name: opensearch-node2
    restart: always
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1
      - network.host=0.0.0.0
    healthcheck:
      test: curl -s  http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./volume/opensearch-data2:/usr/share/opensearch/data
      - ./volume/opensearch-data2-config:/usr/share/opensearch/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - opensearch-net
    logging:
      options:
        max-size: "10m"

  opensearch-node3:
    image: opensearchproject/opensearch:1.2.3
    container_name: opensearch-node3
    restart: always
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1
      - network.host=0.0.0.0
    healthcheck:
      test: curl -s  http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./volume/opensearch-data3:/usr/share/opensearch/data
      - ./volume/opensearch-data3-config:/usr/share/opensearch/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - opensearch-net
    logging:
      options:
        max-size: "10m"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`elk.leminar.ir`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    restart: always
    #  ports:
    #    - 5601:5601
    #  expose:
    #    - "5601"
    healthcheck:
      test: curl http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      OPENSEARCH_URL: https://opensearch-node1:9200
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200","https://opensearch-node3:9200"]' # must be a string with no spaces when specified as an environment variable
    volumes:
      - ./volume/opensearch_dashboards/config:/usr/share/opensearch-dashboards/config
      - ./volume/opensearch_dashboards/plugins:/usr/share/opensearch-dashboards/plugins
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - opensearch-net
    logging:
      options:
        max-size: "10m"

## reverse Proxy
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=rfak.it@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./volume/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - opensearch-net
    logging:
      options:
        max-size: "10m"

  logstash01:
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    container_name: logstash01
    restart: always
    volumes:
      - ./volume/logstash/data:/data
      - ./volume/logstash/pipeline:/usr/share/logstash/pipeline
      - ./volume/logstash/config:/usr/share/logstash/config
#      - ./volume/logstash/geo/GeoLite2-City.mmdb:/usr/share/logstash/GeoLite2-City.mmdb
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5044:5044"
      - "5045:5045/udp"
      - "5046:5046"
    environment:
      LS_JAVA_OPTS: "-Xmx4g -Xms4g"
      PIPELINE_WORKERS: "8"
    networks:
      - opensearch-net
    logging:
      options:
        max-size: "10m"

networks:
  opensearch-net:
